In [3]:
import pandas as pd

df = pd.read_csv("/content/gadget_sales_dataset.csv")
df.head()

,OrderID,Week,Order_Date,Customer_Name,Customer_Age,Country,City,Product,Units_Sold,Price_INR,Marketing_Spend_INR,Discount_Percentage,Payment_Method,Shipping_Status,Delivery_Time_Days,Revenue_INR,Discount_Amount_INR,Final_Amount_INR
0,1,7,2023-01-01 00:00:00,Aditi Verma,33,Japan,Chennai,DSLR Camera,21,32819,29798,13,Cash on Delivery,Shipped,14,689199,89596.0,599603.0
1,2,20,2023-01-01 01:00:00,Yuki Nakamura,59,UAE,Dubai,Wireless Mouse,16,48779,28466,21,UPI,Returned,4,780464,163897.0,616567.0
2,3,15,2023-01-01 02:00:00,Suresh Kumar,47,UK,Hyderabad,Drone,44,66584,28516,10,Net Banking,Returned,13,2929696,292970.0,2636726.0
3,4,11,2023-01-01 03:00:00,Arjun Reddy,33,Germany,Dubai,Earbuds,40,20950,26705,9,Cash on Delivery,Shipped,12,838000,75420.0,762580.0
4,5,8,2023-01-01 04:00:00,Yuki Nakamura,29,UK,Chennai,Power Bank,26,16173,26070,26,Net Banking,Pending,9,420498,109329.0,311169.0

In [4]:
df.dtypes

OrderID                  int64
Week                     int64
Order_Date              object
Customer_Name           object
Customer_Age             int64
Country                 object
City                    object
Product                 object
Units_Sold               int64
Price_INR                int64
Marketing_Spend_INR      int64
Discount_Percentage      int64
Payment_Method          object
Shipping_Status         object
Delivery_Time_Days       int64
Revenue_INR              int64
Discount_Amount_INR    float64
Final_Amount_INR       float64
dtype: object

In [5]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [6]:
df.dtypes

OrderID                         int64
Week                            int64
Order_Date             datetime64[ns]
Customer_Name                  object
Customer_Age                    int64
Country                        object
City                           object
Product                        object
Units_Sold                      int64
Price_INR                       int64
Marketing_Spend_INR             int64
Discount_Percentage             int64
Payment_Method                 object
Shipping_Status                object
Delivery_Time_Days              int64
Revenue_INR                     int64
Discount_Amount_INR           float64
Final_Amount_INR              float64
dtype: object

In [7]:
df.isnull().sum()

OrderID                0
Week                   0
Order_Date             0
Customer_Name          0
Customer_Age           0
Country                0
City                   0
Product                0
Units_Sold             0
Price_INR              0
Marketing_Spend_INR    0
Discount_Percentage    0
Payment_Method         0
Shipping_Status        0
Delivery_Time_Days     0
Revenue_INR            0
Discount_Amount_INR    0
Final_Amount_INR       0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)